modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory (26 is current forge version)

[[mods]] #mandatory
modId="dnamod" #mandatory
version="0.1.0" #mandatory
displayName="Declaring New Apocalypse Mode" #mandatory
credits="Thanks to Harry Talks and NuparuProgramming" #optional
authors="Kan3" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
When the apocalypse will strike the Earth
Who's going to face it until the end?'''

[[dependencies.dnamod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
